name: Next Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@main

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: upload to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync . s3://next-deploy-maxkim --delete --exclude '.github/*' --exclude '.git/*' --exclude '.gitignore'

      - name: deploy to ec2
        run: aws deploy create-deployment --application-name next-deploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name next-deploy --s3-location bucket=next-deploy-maxkim
