name: Next Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@main

      - name: Install Dependencies
        run: npm install

      - name: Build Next App
        run: npm run build

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip . -x *.git* *.gitignore .github/* yarn.lock
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: upload to s3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://next-deploy-maxkim

      - name: Deploy to ec2
        run: aws deploy create-deployment --application-name next-deploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name next-deploy --s3-location bucket=next-deploy-maxkim,bundleType=zip,key=$GITHUB_SHA.zip
