name: Next Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@main

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip . -x *.git* *.gitignore .github/*
        shell: bash

      - name: upload to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://next-deploy-maxkim

      - name: deploy to ec2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws deploy create-deployment --application-name next-deploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name next-deploy --s3-location bucket=next-deploy-maxkim,bundleType=zip,key=$GITHUB_SHA.zip
